# Generated by Django 6.0.6 on 2026-06-12 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=100)),
                ('es_terminal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'estado_expediente',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('modulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('estamento', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_universitario', models.CharField(blank=True, max_length=100, null=True)),
                ('es_abogado', models.BooleanField(default=False)),
                ('titular_a', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='RolProcesal',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rol_procesal',
            },
        ),
        migrations.CreateModel(
            name='SalaAudiencia',
            fields=[
                ('id_sala_aud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('equipada_videoconf', models.BooleanField(default=False)),
                ('enlace_virtual', models.URLField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sala_audiencia',
            },
        ),
        migrations.CreateModel(
            name='SalaTribunal',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sala_tribunal',
            },
        ),
        migrations.CreateModel(
            name='TipoActuacion',
            fields=[
                ('id_tipo_actuacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_actuacion',
            },
        ),
        migrations.CreateModel(
            name='TipoAudiencia',
            fields=[
                ('id_tipo_audiencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_estimada', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_audiencia',
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id_tipo_doc', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('requiere_firma', models.BooleanField(default=False)),
                ('es_publico', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_doc',
            },
        ),
        migrations.CreateModel(
            name='TipoProceso',
            fields=[
                ('id_tipo_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_proceso',
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id_tipo_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_recurso',
            },
        ),
        migrations.CreateModel(
            name='TipoResolucion',
            fields=[
                ('id_tipo_res', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_jerarquico', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_resolucion',
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id_tribunal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tribunal', models.CharField(max_length=200)),
                ('instancia', models.CharField(max_length=100)),
                ('norma_creacion', models.TextField()),
            ],
            options={
                'db_table': 'tribunal',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('numero_expediente', models.CharField(max_length=50, unique=True)),
                ('ano', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_estado_expediente', models.ForeignKey(db_column='id_estado_expediente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='tribunal.estadoexpediente')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='tribunal.salatribunal')),
                ('id_tipo_proceso', models.ForeignKey(db_column='id_tipo_proceso', on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='tribunal.tipoproceso')),
            ],
            options={
                'db_table': 'expediente',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True)),
                ('numero_folio', models.IntegerField(blank=True, null=True)),
                ('hash_integridad', models.CharField(max_length=256)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tamano_kb', models.IntegerField()),
                ('es_electronico', models.BooleanField(default=True)),
                ('firmado_digitalmente', models.BooleanField(default=False)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tribunal.expediente')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='tribunal.persona')),
                ('id_tipo_doc', models.ForeignKey(db_column='id_tipo_doc', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tribunal.tipodoc')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id_audiencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_programada', models.DateTimeField()),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado_audiencia', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('REALIZADA', 'Realizada'), ('FINALIZADA', 'Finalizada'), ('SUSPENDIDA', 'Suspendida')], default='PROGRAMADA', max_length=50)),
                ('motivo_suspension', models.TextField(blank=True, null=True)),
                ('link_videoconferencia', models.URLField(blank=True, null=True)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='tribunal.expediente')),
                ('id_sala_aud', models.ForeignKey(blank=True, db_column='id_sala_aud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiencias', to='tribunal.salaaudiencia')),
                ('id_tipo_audiencia', models.ForeignKey(db_column='id_tipo_audiencia', on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='tribunal.tipoaudiencia')),
            ],
            options={
                'db_table': 'audiencia',
            },
        ),
        migrations.CreateModel(
            name='ParteProcesal',
            fields=[
                ('id_parte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inclusion', models.DateField(auto_now_add=True)),
                ('fecha_exclusion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='tribunal.expediente')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='partes_procesales', to='tribunal.persona')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='tribunal.rolprocesal')),
            ],
            options={
                'db_table': 'parte_procesal',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_denuncia', models.CharField(max_length=50, unique=True)),
                ('fecha_denuncia', models.DateField(auto_now_add=True)),
                ('tipo_denunciado', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('SUBSANACION', 'Subsanación'), ('ADMITIDA', 'Admitida'), ('DECLARACION_INFORMATIVA', 'Declaración Informativa'), ('PRUEBAS', 'Período Probatorio'), ('CONCLUSION', 'Conclusión'), ('RESUELTA', 'Resuelta'), ('APELADA', 'Apelada'), ('EJECUTADA', 'Ejecutada'), ('ARCHIVADA', 'Archivada')], default='REGISTRADA', max_length=30)),
                ('resolucion', models.TextField(blank=True, help_text='Resolución del caso', null=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='tribunal.expediente')),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_recibidas', to='tribunal.persona')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_hechas', to='tribunal.persona')),
            ],
            options={
                'db_table': 'denuncia',
            },
        ),
        migrations.CreateModel(
            name='ContactoPersona',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contacto', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=200)),
                ('es_principal', models.BooleanField(default=False)),
                ('validado', models.BooleanField(default=False)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='tribunal.persona')),
            ],
            options={
                'db_table': 'contacto_persona',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaAudiencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('rol_en_audiencia', models.CharField(max_length=100)),
                ('asistio', models.BooleanField(default=False)),
                ('hora_ingreso', models.DateTimeField(blank=True, null=True)),
                ('motivo_inasistencia', models.TextField(blank=True, null=True)),
                ('id_audiencia', models.ForeignKey(db_column='id_audiencia', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tribunal.audiencia')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='tribunal.persona')),
            ],
            options={
                'db_table': 'asistencia_audiencia',
            },
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id_resolucion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_resolucion', models.CharField(max_length=100)),
                ('fecha_resolucion', models.DateField()),
                ('fecha_notificacion', models.DateField(blank=True, null=True)),
                ('parte_dispositiva', models.TextField()),
                ('fundamentacion', models.TextField()),
                ('estado', models.CharField(default='ACTIVA', max_length=50)),
                ('es_recurrible', models.BooleanField(default=False)),
                ('plazo_recurso_dias', models.IntegerField(default=0)),
                ('id_documento', models.OneToOneField(blank=True, db_column='id_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolucion', to='tribunal.documento')),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='tribunal.expediente')),
                ('id_tipo_res', models.ForeignKey(db_column='id_tipo_res', on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='tribunal.tiporesolucion')),
            ],
            options={
                'db_table': 'resolucion',
            },
        ),
        migrations.CreateModel(
            name='ResolucionAntigua',
            fields=[
                ('id_resolucion_antigua', models.AutoField(primary_key=True, serialize=False)),
                ('numero_resolucion', models.CharField(max_length=50, unique=True)),
                ('fecha_resolucion', models.DateField()),
                ('tipo_sancion', models.CharField(choices=[('SANCION', 'Sanción'), ('ABSOLUCION', 'Absolución'), ('ARCHIVO', 'Archivo')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sancion', models.CharField(blank=True, help_text='Ej: Suspensión 3 meses, Multa, etc.', max_length=200, null=True)),
                ('documento_url', models.URLField(blank=True, null=True)),
                ('persona_denunciada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones_antiguas_denunciada', to='tribunal.persona')),
                ('persona_denunciante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones_antiguas_denunciante', to='tribunal.persona')),
            ],
            options={
                'db_table': 'resolucion_antigua',
            },
        ),
        migrations.AddField(
            model_name='tipoaudiencia',
            name='id_tipo_proceso',
            field=models.ForeignKey(db_column='id_tipo_proceso', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_audiencia', to='tribunal.tipoproceso'),
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_interposicion', models.DateField(auto_now_add=True)),
                ('estado_recurso', models.CharField(default='PENDIENTE', max_length=50)),
                ('fundamentos', models.TextField()),
                ('id_expediente_alzada', models.ForeignKey(blank=True, db_column='id_expediente_alzada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_en_alzada', to='tribunal.expediente')),
                ('id_recurrente', models.ForeignKey(db_column='id_recurrente', on_delete=django.db.models.deletion.CASCADE, related_name='recursos_interpuestos', to='tribunal.parteprocesal')),
                ('id_resolucion_impugnada', models.ForeignKey(blank=True, db_column='id_resolucion_impugnada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_impugnados', to='tribunal.resolucion')),
                ('id_resolucion_respuesta', models.ForeignKey(blank=True, db_column='id_resolucion_respuesta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_respondidos', to='tribunal.resolucion')),
                ('id_tipo_recurso', models.ForeignKey(db_column='id_tipo_recurso', on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='tribunal.tiporecurso')),
            ],
            options={
                'db_table': 'recurso',
            },
        ),
        migrations.AddField(
            model_name='salatribunal',
            name='id_tribunal',
            field=models.ForeignKey(db_column='id_tribunal', on_delete=django.db.models.deletion.CASCADE, related_name='salas_tribunal', to='tribunal.tribunal'),
        ),
        migrations.AddField(
            model_name='salaaudiencia',
            name='id_tribunal',
            field=models.ForeignKey(db_column='id_tribunal', on_delete=django.db.models.deletion.CASCADE, related_name='salas_audiencia', to='tribunal.tribunal'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('paterno', models.CharField(max_length=100)),
                ('materno', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo_oficial', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('otp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='tribunal.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='SolicitudActualizacion',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_ianus', models.CharField(max_length=100)),
                ('codigo_sala', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.CharField(default='PENDIENTE', max_length=50)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='tribunal.usuario')),
            ],
            options={
                'db_table': 'solicitud_actualizacion',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=50)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_diligencia', models.DateTimeField(blank=True, null=True)),
                ('estado_notificacion', models.CharField(default='PENDIENTE', max_length=50)),
                ('id_documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tribunal.documento')),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tribunal.expediente')),
                ('id_parte', models.ForeignKey(db_column='id_parte', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tribunal.parteprocesal')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='tribunal.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('id_estado_anterior', models.ForeignKey(blank=True, db_column='id_estado_anterior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_como_anterior', to='tribunal.estadoexpediente')),
                ('id_estado_nuevo', models.ForeignKey(db_column='id_estado_nuevo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_como_nuevo', to='tribunal.estadoexpediente')),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='tribunal.expediente')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='historial_estados', to='tribunal.usuario')),
            ],
            options={
                'db_table': 'historial_estado',
            },
        ),
        migrations.CreateModel(
            name='ActuacionProcesal',
            fields=[
                ('id_actuacion', models.AutoField(primary_key=True, serialize=False)),
                ('folio_inicio', models.IntegerField()),
                ('folio_fin', models.IntegerField()),
                ('es_publica', models.BooleanField(default=True)),
                ('fecha_actuacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='tribunal.expediente')),
                ('id_tipo_actuacion', models.ForeignKey(db_column='id_tipo_actuacion', on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='tribunal.tipoactuacion')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='actuaciones', to='tribunal.usuario')),
            ],
            options={
                'db_table': 'actuacion_procesal',
            },
        ),
        migrations.CreateModel(
            name='ActaAudiencia',
            fields=[
                ('id_acta', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_acta', models.DateTimeField(auto_now_add=True)),
                ('firmada', models.BooleanField(default=False)),
                ('url_grabacion', models.URLField(blank=True, null=True)),
                ('id_audiencia', models.OneToOneField(db_column='id_audiencia', on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='tribunal.audiencia')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='tribunal.usuario')),
            ],
            options={
                'db_table': 'acta_audiencia',
            },
        ),
        migrations.CreateModel(
            name='VocalTribunal',
            fields=[
                ('id_vocal', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_posesion', models.DateField()),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='vocales', to='tribunal.persona')),
                ('id_sala', models.ForeignKey(blank=True, db_column='id_sala', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocales', to='tribunal.salatribunal')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vocales_registrados', to='tribunal.usuario')),
            ],
            options={
                'db_table': 'vocal_tribunal',
            },
        ),
        migrations.CreateModel(
            name='ConformacionSalaExpediente',
            fields=[
                ('id_conformacion', models.AutoField(primary_key=True, serialize=False)),
                ('rol_en_caso', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('id_expediente', models.ForeignKey(db_column='id_expediente', on_delete=django.db.models.deletion.CASCADE, related_name='conformaciones', to='tribunal.expediente')),
                ('id_vocal', models.ForeignKey(blank=True, db_column='id_vocal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conformaciones', to='tribunal.vocaltribunal')),
            ],
            options={
                'db_table': 'conformacion_sala_expediente',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='tribunal.permiso')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='tribunal.rol')),
            ],
            options={
                'db_table': 'rol_permiso',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
