# Generated by Django 6.0.6 on 2026-06-12 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='sala_asignada',
            field=models.ForeignKey(blank=True, db_column='id_sala', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados', to='tribunal.salatribunal'),
        ),
    ]
