# Generated by Django 6.0.6 on 2026-06-12 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_denuncia', models.CharField(max_length=50, unique=True)),
                ('fecha_denuncia', models.DateField(auto_now_add=True)),
                ('tipo_denunciado', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_TRAMITE', 'En Trámite'), ('RESUELTA', 'Resuelta'), ('APELADA', 'Apelada'), ('ARCHIVADA', 'Archivada')], default='REGISTRADA', max_length=20)),
                ('resolucion', models.TextField(blank=True, help_text='Resolución del caso', null=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_recibidas', to='tribunal.persona')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_hechas', to='tribunal.persona')),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='tribunal.expediente')),
            ],
            options={
                'db_table': 'denuncia',
            },
        ),
        migrations.CreateModel(
            name='ResolucionAntigua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(max_length=50, unique=True)),
                ('fecha_resolucion', models.DateField()),
                ('tipo_sancion', models.CharField(choices=[('SANCION', 'Sanción'), ('ABSOLUCION', 'Absolución'), ('ARCHIVO', 'Archivo')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sancion', models.CharField(blank=True, help_text='Ej: Suspensión 3 meses, Multa, etc.', max_length=200, null=True)),
                ('documento_url', models.URLField(blank=True, null=True)),
                ('persona_afectada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones_antiguas', to='tribunal.persona')),
            ],
            options={
                'db_table': 'resolucion_antigua',
            },
        ),
    ]
