# Generated by Django 6.0.5 on 2026-06-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0002_denuncia_resolucionantigua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('SUBSANACION', 'Subsanación'), ('ADMITIDA', 'Admitida'), ('DECLARACION_INFORMATIVA', 'Declaración Informativa'), ('PRUEBAS', 'Período Probatorio'), ('CONCLUSION', 'Conclusión'), ('RESUELTA', 'Resuelta'), ('APELADA', 'Apelada'), ('EJECUTADA', 'Ejecutada'), ('ARCHIVADA', 'Archivada')], default='REGISTRADA', max_length=30),
        ),
    ]
