# Generated by Django 6.0.5 on 2026-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0002_usuario_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencia',
            name='estado_audiencia',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('REALIZADA', 'Realizada'), ('FINALIZADA', 'Finalizada'), ('SUSPENDIDA', 'Suspendida')], default='PROGRAMADA', max_length=50),
        ),
    ]
