# Generated by Django 6.0.6 on 2026-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0002_rol_sala_asignada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoexpediente',
            options={'ordering': ['nivel']},
        ),
        migrations.AddField(
            model_name='estadoexpediente',
            name='nivel',
            field=models.IntegerField(default=0, help_text='Nivel jerárquico del estado (0=inicial, 1,2,3...)'),
        ),
    ]
