# Generated by Django 6.0.5 on 2026-06-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0003_alter_denuncia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucionantigua',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resolucionantigua',
            name='persona_afectada',
        ),
        migrations.AddField(
            model_name='resolucionantigua',
            name='id_resolucion_antigua',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='resolucionantigua',
            name='persona_denunciada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones_antiguas_denunciada', to='tribunal.persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resolucionantigua',
            name='persona_denunciante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones_antiguas_denunciante', to='tribunal.persona'),
        ),
    ]
