# Generated by Django 6.0.5 on 2026-06-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0003_alter_estadoexpediente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='acta_conciliacion',
            field=models.TextField(blank=True, help_text='Puntos acordados en la conciliación (Art. 59)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='detalle_sancion',
            field=models.CharField(blank=True, help_text='Ej: Suspensión 3 meses, Multa 15%, etc.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_apelacion',
            field=models.DateField(blank=True, help_text='Fecha en que se interpuso el recurso de apelación', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_conciliacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_hecho',
            field=models.DateField(blank=True, help_text='Fecha en que se cometió la falta. Prescribe a los 2 años (Art. 8)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_remision_superior',
            field=models.DateField(blank=True, help_text='Fecha en que se remitió al Tribunal Superior (Art. 86)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_retiro',
            field=models.DateField(blank=True, help_text='Fecha en que el denunciante retiró la denuncia (Art. 22)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='motivo_retiro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='resolucion_apelacion',
            field=models.TextField(blank=True, help_text='Resolución de segunda instancia recibida', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tipo_resolucion',
            field=models.CharField(blank=True, choices=[('SANCIONATORIA', 'Sancionatoria'), ('ABSOLUTORIA', 'Absolutoria')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tipo_sancion',
            field=models.CharField(blank=True, choices=[('MULTA', 'Multa hasta 20% haber mensual'), ('SUSPENSION_TEMPORAL', 'Suspensión temporal (1 mes - 1 año)'), ('REMOCION', 'Remoción del cargo'), ('RETIRO', 'Retiro de la Universidad'), ('AMONESTACION', 'Amonestación por escrito'), ('SUSPENSION_ESTUDIANTE', 'Suspensión temporal (6 meses - 3 años)'), ('EXPULSION', 'Expulsión de la Universidad')], help_text='Sanción específica impuesta (solo si resolución es Sancionatoria)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('SUBSANACION', 'Subsanación'), ('RETIRADA', 'Retirada'), ('ADMITIDA', 'Admitida'), ('CONCILIADA', 'Conciliada'), ('DECLARACION_INFORMATIVA', 'Declaración Informativa'), ('PRUEBAS', 'Período Probatorio'), ('CONCLUSION', 'Conclusión'), ('RESUELTA', 'Resuelta'), ('APELADA', 'Apelada'), ('EJECUTADA', 'Ejecutada'), ('ARCHIVADA', 'Archivada')], default='REGISTRADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='resolucion',
            field=models.TextField(blank=True, help_text='Parte dispositiva de la resolución final', null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo_denunciado',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRATIVO', 'Administrativo'), ('AUTORIDAD', 'Autoridad')], max_length=20),
        ),
    ]
