# Generated by Django 6.0.5 on 2026-06-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0004_denuncia_acta_conciliacion_denuncia_detalle_sancion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='aclaracion_enmienda',
            field=models.TextField(blank=True, help_text='Texto de la aclaración, complementación o enmienda a la resolución (Art. 77)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_compulsa',
            field=models.DateField(blank=True, help_text='Fecha de interposición del recurso de compulsa (Art. 83)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_desistimiento',
            field=models.DateField(blank=True, help_text='Fecha del desistimiento del denunciante (Art. 23 — solo aplica a su acción, proceso continúa)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_fallecimiento_denunciado',
            field=models.DateField(blank=True, help_text='Fecha de fallecimiento del denunciado — concluye el proceso (Art. 80)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_medidas_precautorias',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_notificacion_resolucion',
            field=models.DateField(blank=True, help_text='Fecha en que se practicó la notificación personal de la resolución definitiva (Art. 46 — máx. 5 días hábiles)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_solicitud_aclaracion',
            field=models.DateField(blank=True, help_text='Fecha en que se solicitó aclaración/complementación (Art. 77 — 2 días hábiles)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='medidas_precautorias',
            field=models.TextField(blank=True, help_text='Descripción de medidas precautorias adoptadas por el Tribunal (Art. 61)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='motivo_desistimiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='resolucion_compulsa',
            field=models.TextField(blank=True, help_text='Resolución del Tribunal Superior sobre la compulsa (Art. 85)', null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('SUBSANACION', 'Subsanación'), ('RETIRADA', 'Retirada'), ('ADMITIDA', 'Admitida'), ('CONCILIADA', 'Conciliada'), ('DECLARACION_INFORMATIVA', 'Declaración Informativa'), ('PRUEBAS', 'Período Probatorio'), ('CONCLUSION', 'Conclusión'), ('RESUELTA', 'Resuelta'), ('APELADA', 'Apelada'), ('EJECUTADA', 'Ejecutada'), ('ARCHIVADA', 'Archivada'), ('PRESCRITA', 'Prescrita'), ('FALLECIDO', 'Fallecido'), ('DESISTIDA', 'Desistida')], default='REGISTRADA', max_length=30),
        ),
    ]
