# Generated by Django 6.0.5 on 2026-06-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0005_denuncia_aclaracion_enmienda_denuncia_fecha_compulsa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='fecha_registro_gaceta',
            field=models.DateField(blank=True, help_text='Fecha de registro de la resolución sancionatoria en la Gaceta Universitaria (Art. 7 — 5 días hábiles)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_remision_rectorado',
            field=models.DateField(blank=True, help_text='Fecha en que el Tribunal remitió el expediente al Rectorado (Art. 16 — 3 días hábiles desde ejecutoria)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_resolucion_rectoral',
            field=models.DateField(blank=True, help_text='Fecha en que el Rector emitió la resolución administrativa (Art. 90 par. II — 5 días hábiles)', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='numero_gaceta',
            field=models.CharField(blank=True, help_text='Número o referencia de la Gaceta Universitaria donde se publicó la resolución', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='numero_resolucion_rectoral',
            field=models.CharField(blank=True, help_text='Número de la resolución administrativa emitida por el Rector', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='observaciones_ejecucion',
            field=models.TextField(blank=True, help_text='Observaciones sobre la ejecución del fallo y cumplimiento por el Rectorado', null=True),
        ),
    ]
