# Generated by Django 6.0.5 on 2026-06-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0006_denuncia_fecha_registro_gaceta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_presentacion',
            field=models.CharField(blank=True, choices=[('ORIGINAL', 'Original'), ('COPIA_LEGALIZADA', 'Fotocopia legalizada'), ('COPIA_SIMPLE', 'Fotocopia simple'), ('DIGITAL', 'Digital')], help_text='Tipo de presentación del documento (Art. 65)', max_length=20, null=True),
        ),
    ]
