from django.contrib import admin
from .models import *

admin.site.register(Permiso)
admin.site.register(Rol)
admin.site.register(RolPermiso)
admin.site.register(Usuario)
admin.site.register(Tribunal)
admin.site.register(EstadoExpediente)
admin.site.register(TipoProceso)
admin.site.register(TipoAudiencia)
admin.site.register(TipoRecurso)
admin.site.register(TipoResolucion)
admin.site.register(TipoDoc)
admin.site.register(TipoActuacion)
admin.site.register(RolProcesal)
admin.site.register(SalaTribunal)
admin.site.register(SalaAudiencia)
admin.site.register(Persona)
admin.site.register(VocalTribunal)
admin.site.register(Expediente)
admin.site.register(ConformacionSalaExpediente)
admin.site.register(HistorialEstado)
admin.site.register(ParteProcesal)
admin.site.register(Documento)
admin.site.register(Audiencia)
admin.site.register(ActaAudiencia)
admin.site.register(AsistenciaAudiencia)
admin.site.register(ContactoPersona)
admin.site.register(Resolucion)
admin.site.register(Recurso)
admin.site.register(ActuacionProcesal)
admin.site.register(Notificacion)
admin.site.register(SolicitudActualizacion)